apiVersion: v1
kind: Secret
metadata:
  name: machine-secrets
type: Opaque
stringData:
  connection-string: "Host=postgres-service;Port=5432;Database=factoryfloor_machines;Username=postgres;Password=postgres"
  jwt-secret: "your-super-secret-key-minimum-32-characters-long!"