apiVersion: v1
kind: Secret
metadata:
  name: identity-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  connection-string: "Host=postgres-service;Port=5432;Database={{ .Values.identityService.database }};Username=postgres;Password={{ .Values.postgres.password }}"
  jwt-secret: {{ .Values.global.jwtSecret | quote }}
  postgres-password: {{ .Values.postgres.password | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: machine-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  connection-string: "Host=postgres-service;Port=5432;Database={{ .Values.machineService.database }};Username=postgres;Password={{ .Values.postgres.password }}"
  jwt-secret: {{ .Values.global.jwtSecret | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: gateway-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  jwt-secret: {{ .Values.global.jwtSecret | quote }}