global:
  jwtSecret: "your-super-secret-key-minimum-32-characters-long!"
  jwtIssuer: "FactoryFloor"
  jwtAudience: "FactoryFloor"

postgres:
  image: postgres:16
  password: postgres
  replicas: 1
  storage: 1Gi

rabbitmq:
  image: rabbitmq:3-management
  username: guest
  password: guest
  replicas: 1

identityService:
  image: factoryfloor-identity:latest
  replicas: 1
  database: factoryfloor_identity

machineService:
  image: factoryfloor-machine:latest
  replicas: 1
  database: factoryfloor_machines
  hpa:
    minReplicas: 1
    maxReplicas: 5
    cpuThreshold: 50
    memoryThreshold: 70

notificationService:
  image: factoryfloor-notification:latest
  replicas: 1

gateway:
  image: factoryfloor-gateway:latest
  replicas: 1